### ISSUE TITLE
NOT WORKING SOLVED ISSUE : Error loading the dashboard strategy

### ISSUE THREAD

**Issue by insol-do** [DigiLive/mushroom-strategy#121] opened 2024-01-25 15:35 UTC
### Discussed in https://github.com/AalianKhan/mushroom-strategy/discussions/120

<div type='discussions-op-text'>

<sup>Originally posted by **insol-do** January 25, 2024</sup>
After trying to make the fix from the resolved issue, it it still not working.
Followed below...
https://github.com/AalianKhan/mushroom-strategy/discussions/90 </div>

**Comment by DigiLive** [comment] 2024-01-26 08:20
Duplicate of #120

**Closed as completed by DigiLive** 2024-01-26 08:20 UTC
Labels: duplicate
